# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGZnXZ2Gh7X7Cty-0qTSuacY_Q-CnPzl

**Task 06: Modifying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials"

"""Read the RDF file as shown in class"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

# we add the University class to the graph
g.add((ns.University, RDF.type, RDFS.Class))

# TO DO
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

# we add "Researcher" as a subclass of "Person"
g.add((ns.Researcher, RDFS.subClassOf, ns.Person))

# TO DO
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smithers"**"""

# new individual of Researcher named "Jane Smithers"
jane_smithers = ns.JaneSmithers
g.add((jane_smithers, RDF.type, ns.Researcher))

# TO DO
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.4: Add to the individual JaneSmithers the email address, fullName, given and family names. Use the https://schema.org vocabulary**"""

schema = Namespace("https://schema.org/")

# we add email, fullName, givenName, and familyName to the individual JaneSmithers
g.add((jane_smithers, schema.email, Literal("janesmithers@gmail.com")))
g.add((jane_smithers, schema.fullName, Literal("Jane Smithers")))
g.add((jane_smithers, schema.givenName, Literal("Jane")))
g.add((jane_smithers, schema.familyName, Literal("Smithers")))

# TO DO
# Visualize the results
for s, p, o in g:
    print(s, p, o)

"""**TASK 6.5: Add UPM as the university where John Smith works. Use the "https://example.org/ namespace**"""

# we define the new namespace for example organization
ns_example = Namespace("https://example.org/")

# we create a new individual for "UPM" and add the property that John Smith works there
upm = ns_example.UPM
g.add((upm, RDF.type, ns_example.University))
g.add((ns.JohnSmith, ns_example.worksAt, upm))

# TO DO
# Visualize the results
for s, p, o in g:
    print(s, p, o)

"""**Task 6.6: Add that Jown knows Jane using the FOAF vocabulary. Make sure the relationship exists.**"""

from rdflib.namespace import FOAF

g.add((ns.JohnSmith, FOAF.knows, jane_smithers))

# TO DO
# Visualize the results

for s, p, o in g:
    print(s, p, o)